/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegistriesRouteImport } from './routes/registries'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServersNameRouteImport } from './routes/servers.$name'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistriesRoute = RegistriesRouteImport.update({
  id: '/registries',
  path: '/registries',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersNameRoute = ServersNameRouteImport.update({
  id: '/servers/$name',
  path: '/servers/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/registries': typeof RegistriesRoute
  '/settings': typeof SettingsRoute
  '/servers/$name': typeof ServersNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/registries': typeof RegistriesRoute
  '/settings': typeof SettingsRoute
  '/servers/$name': typeof ServersNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/registries': typeof RegistriesRoute
  '/settings': typeof SettingsRoute
  '/servers/$name': typeof ServersNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/browse' | '/registries' | '/settings' | '/servers/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/browse' | '/registries' | '/settings' | '/servers/$name'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/registries'
    | '/settings'
    | '/servers/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  RegistriesRoute: typeof RegistriesRoute
  SettingsRoute: typeof SettingsRoute
  ServersNameRoute: typeof ServersNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registries': {
      id: '/registries'
      path: '/registries'
      fullPath: '/registries'
      preLoaderRoute: typeof RegistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$name': {
      id: '/servers/$name'
      path: '/servers/$name'
      fullPath: '/servers/$name'
      preLoaderRoute: typeof ServersNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  RegistriesRoute: RegistriesRoute,
  SettingsRoute: SettingsRoute,
  ServersNameRoute: ServersNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
